Move kiwipy/rmq related modules into a specific module
aiidateam/plumpy pull request #297
Opened 2024-12-12 10:58 UTC by unkcpz

The refactoring is targeting to decouple the dependencies of using kiwipy+rmq as the communicator for the process control. 
One of the major change here is hand write the resolver of future by mimic how tho asyncio does for wrapping `concurrent.futures.Future` into `asyncio.Future`. I use the same way to convert `asyncio.Future` into `concurent.futures.Future` (which is the `kiwipy.Future` as alias). 

- [ ] `CancellableAction` using composite to behave as a Future like object.
- [x] Revert alias of asyncio.Future to plumpy.Future and 
- [ ] revert alias of concurrent.futures.Future to kiwipy.Future.
- [ ] Hand write `_chain` and `_copy_future` since we can not just rely on the API of asyncio that is not exposed.

2024-12-17 22:14 UTC, unkcpz commented on tests/utils.py
> +        del self._rpc_subscribers
This is the Mocked in memory coordinator that in principle can work with sqlite in presto and make it able to submit the calculations.

2025-01-10 22:08 UTC, unkcpz commented
Hi @sphuber, would be great if you can have a look at this, at least make sure no big design issues here. It is not ready because when I port it to aiida-core, it seems work for python3.12 but for python3.9 I can not start the daemon (stuck at daemonize function of circus.). It surely requires more effort to get it proper implemented.

2025-01-11 08:24 UTC, sphuber commented
Can try to find some time at some point but this is a big change, so would require quite some time.

2025-01-31 10:58 UTC, agoscinski commented on src/plumpy/rmq/communications.py
> +T = TypeVar('T', bound=kiwipy.Communicator)
Can we give more meaningful name?
```suggestion
SubtypeCommunicator = TypeVar('SubtypeCommunicator', bound=kiwipy.Communicator)
```
or
```suggestion
CommunicatorT = TypeVar('CommunicatorT', bound=kiwipy.Communicator)
```
or anything else that references that it comes from `Communicator`

2025-02-02 09:25 UTC, unkcpz commented on src/plumpy/rmq/communications.py
> +T = TypeVar('T', bound=kiwipy.Communicator)
Would be better, I'll change.

2025-02-02 09:28 UTC, unkcpz commented on src/plumpy/rmq/communications.py
>  ) -> Callable[..., kiwipy.Future]:
> plumpy.futures to concurrent.futures, my reasoning there was that if we don't have a motivation to change the default type (concurrent.futures.Future) then we can just use it to simplify the code. Then we should also replace kiwipy.Future to concurrent.futures.Future.

The original goal was to clarify these two use cases. In plumpy, the `plumpy.future` is actually alias of `asyncio.Future`, while `kiwipy.future` is for `concurrent.futures.Future` which can not be await and used for thread communication. 
I revert the kiwipy.Future back to be more conservative, but we should make it clear just use the correct future type which make our life easier in the future.

2025-02-21 14:28 UTC, agoscinski reviewed
This PR introduces abstractions for the the process controller and communicator and creates specific implementations for rabbitmq into the submodule `rmq`.

It moves the controller `RemoteProcessController` and `RemoteProcessThreadController ` from submodule `process_comms` to  `rmq.process_control`. A `ProcessController` protocol is introduced in submodule `controller`.

Furthermore, the communicator is replaced with a coordinator in the code. The coordinator takes a communicator and "manages" it. It basically makes it more flexible what kind of how the communication is implemented as long as a `Coordinator` protocol (found in submodule `coordinator`) can be implemented.

in submodule `futures` the `unwrap_kiwi_future` has been moved to `rmq.futures` and `create_task` is simplified. Also `capture_exceptions ` has been introduced. Not sure if logic of `create_task` has changed, but I think these are mainly minor improvements.

A new submodule is introduced `message` which contains the parts relevant parts for creating  messages that can be send over the coordinator (`MessageBuilder)` and launch processes. These have been moved from from submodule `process_comms`.

2025-02-21 14:28 UTC, agoscinski commented on src/plumpy/rmq/futures.py
> +            with kiwipy.capture_exceptions(unwrapping):
Should this still be `kiwipy.capture_exceptions` or `capture_exceptions`?

2025-02-21 14:28 UTC, agoscinski commented on src/plumpy/rmq/process_control.py
> +# FIXME: the class not fit typing of ProcessController protocol
What is the idea here to fix this? Just the class?

2025-02-21 16:15 UTC, agoscinski commented
Name of coordinator, because it only coordinates the messages for the workers (but does not coordinates the processes)

Regarding
> TODO in future PR: use async RemoteProcessController in aiida-core.

We can use `RemoteProcessThreadController` (async version of `RemoteProcessController`) in the future but these need subsequent changes aiida-core so not in this PR @unkcpz will create issue for this.

2025-02-21 16:16 UTC, agoscinski commented on src/plumpy/rmq/process_control.py
> +# FIXME: the class not fit typing of ProcessController protocol
Okay this was regarding the return type that needs to consider the asyncio future type, that needs to be done in the protocol then it can support the `RemoteProcessThreadController` and `RemoteProcessController`

2025-02-21 16:17 UTC, agoscinski commented on src/plumpy/futures.py
> +    return asyncio.wrap_future(asyncio.run_coroutine_threadsafe(coro(), loop))
Might have another look at it, but it is more implementation details then really general logic. Would be also useful to check in review but takes a lot of time to understand.

2025-02-21 16:19 UTC, agoscinski commented on src/plumpy/message.py
> +    async def __call__(self, coordinator: Coordinator, task: Dict[str, Any]) -> Union[PID_TYPE, Any]:
This is something related to rmq that it wants the coordinator/communicator in the first argument, but this could be forwarded to the RMQ implementation of the coordinator by wrapping functions. Check in second review if adapted.

2025-02-21 16:19 UTC, agoscinski commented on src/plumpy/rmq/process_control.py
> +# FIXME: the class not fit typing of ProcessController protocol
Check in second review if adapted.

2025-02-21 22:53 UTC, unkcpz commented on src/plumpy/rmq/communications.py
> +T = TypeVar('T', bound=kiwipy.Communicator)
https://github.com/aiidateam/plumpy/pull/297/commits/00d5be962504b19f838e9202d98f281dbe59e078

2025-02-21 22:55 UTC, unkcpz commented on src/plumpy/message.py
> +    async def __call__(self, coordinator: Coordinator, task: Dict[str, Any]) -> Union[PID_TYPE, Any]:
I change it to `call` and use it as `hook_task_receiver(ProcessLaunch().call)`. I change the name from `add_task_subscriber` to `hook_task_receiver` for coordinator. Same for rpc/broadcast.

2025-02-24 09:32 UTC, unkcpz commented on tests/rmq/test_process_control.py
> +    coordinator = RmqCoordinator(comm)
This is a typical example how I wrap the original rmq communicator into the Coordinator interface.

2025-02-24 09:33 UTC, unkcpz commented on src/plumpy/coordinator.py
> +    def unhook_task_receiver(self, identifier: 'ID_TYPE') -> None: ...
I rename the interfaces to distinguish the coordinator from rmq communicator.

2025-02-26 14:01 UTC, agoscinski requested changes
Need to pause review. Posting what I have so far now.

2025-02-26 15:33 UTC, agoscinski requested changes

2025-02-26 15:33 UTC, agoscinski commented on src/plumpy/rmq/futures.py
> +# XXX: this required in aiida-core, see if really need this unwrap.
Did you change the logic somewhere that it does not need to be unwrapped? I am actually not sure anymore why we have these nested Futures.

2025-02-26 15:38 UTC, agoscinski commented on src/plumpy/broadcast_filter.py
> +        return 'BroadcastFilter'
talked with @unkcpz he will refactor the class anyway in the future. Right now it is just a copy of kiwipy so it is better to change it in another PR

2025-02-26 15:38 UTC, agoscinski commented on src/plumpy/broadcast_filter.py
> +    def __call__(self, body, sender=None, subject=None, correlation_id=None):
talked with @unkcpz he will refactor the class anyway in the future. Right now it is just a copy of kiwipy so it is better to change it in another PR

2025-02-26 21:00 UTC, unkcpz commented on tests/utils.py
> +class MockCoordinator:
Just give it a try. For MockCoordinator, sure, didn't see the power of protocol. When it comes to `RmqCoordinator` where I want to have a generic typing support for the inner communicator (in aiida, it is `LoopCommunicator`, in plumpy, there are `RmqCommunicator` and `RmqThreadCommunicator`). 
I am sure there should be ways to workaround this:

```
tests/rmq/__init__.py:19: in <module>
    class RmqCoordinator(Generic[U], Coordinator):
../../.local/share/uv/python/cpython-3.9.21-linux-x86_64-gnu/lib/python3.9/abc.py:106: in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
E   TypeError: Cannot create a consistent method resolution
E   order (MRO) for bases Generic, Coordinator
```

I believe this can make our life a bit uneasy when it comes to define more generic types that need to work with static type checking.

It is a valid point that the test is better to add, so I add `runtime_checkable` to `Coordinator` and have two tests for `MockCoordinator` and `RmqCoordinator` respectively. (https://github.com/aiidateam/plumpy/pull/297/commits/4242057d4778aca1d2e039745c605e0c09dc6a4e)

2025-02-26 21:09 UTC, unkcpz commented on src/plumpy/rmq/process_control.py
> +class RemoteProcessController:
Agree, I inherit for both, these two controllers do not need to be generic. Make a lot sense to just explicitly declaring the implementation.

2025-02-26 21:11 UTC, unkcpz commented on tests/utils.py
> +class MockCoordinator:
Okay, that was my skill issue. What I should do is:

```python
class RmqCoordinator(Coordinator, Generic[U]):
    ...
```

2025-02-27 04:45 UTC, agoscinski commented on tests/utils.py
> +class MockCoordinator:
Was the inheritance order important or what was the issue something else?

2025-02-27 04:51 UTC, agoscinski approved these changes
Added comments for future changes in the dev branch to PR #319

2025-02-27 10:41 UTC, unkcpz commented on tests/utils.py
> +class MockCoordinator:
A note for my self. 
In the current situation, there is no actually benefit to use protocol over abc class. I can just argue it is a bit more "flexible", with the cost of losing the explicity.  The advantage only shows up when there is another implementation that has its own way to use its own "Coordinator" then making `RmqCoordinator` to work with that case without inherit can be only possible with protocol. But we never need to get there. 

Therefore, the style will be using protocol but explicitly inherit from it for subclass.

2025-02-27 10:51 UTC, merged

2025-02-27 10:52 UTC, unkcpz commented
It is rebased and merged to `dev` branch. Many many thanks for the review @agoscinski!